### ISSUE TITLE
Which mule version support @Config?

### ISSUE THREAD

**Issue by marjan4jc** [mulesoft/cmis-connector#29]
@Config [config] within the connector [cmis] is not supported in mule 3.6.1; nested exception is java.lang.NoClassDefFoundError: org/mule/security/oauth/config/AbstractDevkitBasedDefinitionParser

I want to use cmis-connector ver. 2.0.0 but with all mule versions that I tried 3.6.0, 3.6.1, 3.5.0, 3.5.0-bighorn etc. I got the exception above. cmis-connector ver 1.14.1 is working ok with bighorn. I need 2.0.0 to make it work with 3.6.1. What is a appropriate mule version that need to be used with cmis connector 2.0.0? Any suggestions?

**Comment by karthikanantha** [comment]
The issue doesn't seem to be with CMIS connector. I have verified it in 3.6.x versions of mule and works perfectly. CMIS v2.0 works with all 3.5+ versions of mule.
